// <auto-generated />
using System;
using MagnificentMovieMenu.MagnificentMovieMenu;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MagnificentMovieMenu.Migrations
{
    [DbContext(typeof(moviesContext))]
    [Migration("20190228231405_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("MagnificentMovieMenu.MagnificentMovieMenu.List", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int(11)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("List","movies");
                });

            modelBuilder.Entity("MagnificentMovieMenu.MagnificentMovieMenu.Movie", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int(11)");

                    b.Property<string>("Category")
                        .HasMaxLength(45)
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false);

                    b.Property<int?>("Rating")
                        .HasColumnType("int(11)");

                    b.Property<int?>("Year")
                        .HasColumnType("int(11)");

                    b.HasKey("Id");

                    b.ToTable("Movie","movies");
                });
#pragma warning restore 612, 618
        }
    }
}
