// <auto-generated />
using System;
using MagnificentMovieMenu.AzureDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MagnificentMovieMenu.Migrations
{
    [DbContext(typeof(moviesContext))]
    partial class moviesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MagnificentMovieMenu.AzureDbContext.List", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int(11)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("list","movies");
                });

            modelBuilder.Entity("MagnificentMovieMenu.AzureDbContext.Movie", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int(11)");

                    b.Property<string>("Category")
                        .HasMaxLength(45)
                        .IsUnicode(false);

                    b.Property<string>("Img")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false);

                    b.Property<int?>("Rating")
                        .HasColumnType("int(11)");

                    b.Property<string>("Slug")
                        .HasMaxLength(45)
                        .IsUnicode(false);

                    b.Property<int?>("Year")
                        .HasColumnType("int(11)");

                    b.HasKey("Id");

                    b.ToTable("movie","movies");
                });
#pragma warning restore 612, 618
        }
    }
}
