// <auto-generated />
using System;
using MagnificentMovieMenu.movies;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MagnificentMovieMenu.Migrations
{
    [DbContext(typeof(moviesContext))]
    partial class moviesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("MagnificentMovieMenu.movies.Movie", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int(11)");

                    b.Property<string>("Category")
                        .HasMaxLength(45)
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .IsUnicode(false);

                    b.Property<int?>("Rating")
                        .HasColumnType("int(11)");

                    b.Property<int?>("Year")
                        .HasColumnType("int(11)");

                    b.HasKey("Id");

                    b.ToTable("Movie","movies");
                });

            modelBuilder.Entity("MagnificentMovieMenu.movies.Movies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(10) unsigned");

                    b.Property<string>("Category")
                        .HasColumnName("category")
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.Property<int?>("Rating")
                        .HasColumnName("rating")
                        .HasColumnType("int(11)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("title")
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.Property<short?>("Year")
                        .HasColumnName("year")
                        .HasColumnType("year(4)");

                    b.HasKey("Id");

                    b.ToTable("movies","movies");
                });
#pragma warning restore 612, 618
        }
    }
}
