// <auto-generated />
using MoviesModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Movies.Migrations
{
  [DbContext(typeof(MoviesContext))]
  partial class MoviesContextModelSnapshot : ModelSnapshot
  {
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

      modelBuilder.Entity("ConsoleApp.SQLite.Movie", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd();

            b.Property<string>("Category");

            b.Property<string>("Name");

            b.Property<int>("Rating");

            b.Property<int>("Year");

            b.HasKey("Id");

            b.ToTable("Movies");
          });
#pragma warning restore 612, 618
    }
  }
}
